version: '3'
services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-container
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
