version: '3'
services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - store_default

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-container
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    networks:
      - store_default

networks:
  store_default:
    external: true

#sudo docker run -d -p 80:8080 public.ecr.aws/q0l1o8q5/bookstore:latest --spring.datasource.url=jdbc:mysql://mysql-container:3306/store --spring.datasource.username=root --spring.datasource.password=root